use crate::win32::*;

#[repr(u32)]
#[derive(PartialEq, Eq, Clone, Copy, Debug)]
#[allow(dead_code)] // Unused variants
/// MSDN: [D3D_PRIMITIVE_TOPOLOGY](https://docs.microsoft.com/en-us/windows/desktop/api/d3dcommon/ne-d3dcommon-d3d_primitive_topology)
pub enum PrimitiveTopology {
    Undefined                   = D3D_PRIMITIVE_TOPOLOGY_UNDEFINED,
    PointList                   = D3D_PRIMITIVE_TOPOLOGY_POINTLIST,
    LineList                    = D3D_PRIMITIVE_TOPOLOGY_LINELIST,
    LineStrip                   = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP,
    TriangleList                = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
    TriangleStrip               = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
    LineListAdj                 = D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,
    LineStripAdj                = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,
    TriangleListAdj             = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,
    TriangleStripAdj            = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ,
    _1ControlPointPatchList     = D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST,
    _2ControlPointPatchList     = D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST,
    _3ControlPointPatchList     = D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST,
    _4ControlPointPatchList     = D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST,
    _5ControlPointPatchList     = D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST,
    _6ControlPointPatchList     = D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST,
    _7ControlPointPatchList     = D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST,
    _8ControlPointPatchList     = D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST,
    _9ControlPointPatchList     = D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST,
    _10ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST,
    _11ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST,
    _12ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST,
    _13ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST,
    _14ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST,
    _15ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST,
    _16ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST,
    _17ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST,
    _18ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST,
    _19ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST,
    _20ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST,
    _21ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST,
    _22ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST,
    _23ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST,
    _24ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST,
    _25ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST,
    _26ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST,
    _27ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST,
    _28ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST,
    _29ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST,
    _30ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST,
    _31ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST,
    _32ControlPointPatchList    = D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST,
}

impl PrimitiveTopology {
    pub fn raw(self) -> D3D_PRIMITIVE_TOPOLOGY { self as D3D_PRIMITIVE_TOPOLOGY }
}
